"""Specify foreign keys in Post model

Revision ID: 765d008a9187
Revises: 819e1871d041
Create Date: 2024-12-12 17:07:55.658416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '765d008a9187'
down_revision = '819e1871d041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
